// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.mybriefcase_bookmarks_ffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_mybriefcase_bookmarks_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_mybriefcase_bookmarks_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "mybriefcase_bookmarks_ffi"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}






























































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "mybriefcase_bookmarks_ffi")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_add_bookmark(`folderId`: RustBuffer.ByValue,`url`: RustBuffer.ByValue,`title`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_create_folder(`parentFolderId`: RustBuffer.ByValue,`title`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_delete_bookmark(`bookmarkId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_delete_folder(`folderId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_export_html(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_get_bookmark(`bookmarkId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_get_bookmark_history(`bookmarkId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_get_folder_children(`folderId`: RustBuffer.ByValue,`sortBy`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_get_folder_nav_tree(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_import_html(`folderId`: RustBuffer.ByValue,`html`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_init_repo(`dataDir`: RustBuffer.ByValue,`syncDir`: RustBuffer.ByValue,`clientId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_move_item(`itemId`: RustBuffer.ByValue,`fromFolderId`: RustBuffer.ByValue,`toFolderId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_rename_folder(`folderId`: RustBuffer.ByValue,`title`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_revert_bookmark(`bookmarkId`: RustBuffer.ByValue,`changeHash`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_search_bookmarks(`query`: RustBuffer.ByValue,`sortBy`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_shutdown(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_trigger_full_merge(uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_mybriefcase_bookmarks_ffi_fn_func_update_bookmark(`bookmarkId`: RustBuffer.ByValue,`url`: RustBuffer.ByValue,`title`: RustBuffer.ByValue,`notes`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_mybriefcase_bookmarks_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_mybriefcase_bookmarks_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_mybriefcase_bookmarks_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_add_bookmark(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_create_folder(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_delete_bookmark(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_delete_folder(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_export_html(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_get_bookmark(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_get_bookmark_history(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_get_folder_children(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_get_folder_nav_tree(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_import_html(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_init_repo(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_move_item(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_rename_folder(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_revert_bookmark(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_search_bookmarks(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_shutdown(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_trigger_full_merge(
    ): Short
    fun uniffi_mybriefcase_bookmarks_ffi_checksum_func_update_bookmark(
    ): Short
    fun ffi_mybriefcase_bookmarks_ffi_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_mybriefcase_bookmarks_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_add_bookmark() != 5196.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_create_folder() != 25980.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_delete_bookmark() != 8917.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_delete_folder() != 30490.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_export_html() != 12712.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_get_bookmark() != 4562.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_get_bookmark_history() != 60069.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_get_folder_children() != 959.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_get_folder_nav_tree() != 12627.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_import_html() != 12226.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_init_repo() != 48495.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_move_item() != 44918.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_rename_folder() != 48976.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_revert_bookmark() != 20674.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_search_bookmarks() != 32213.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_shutdown() != 40517.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_trigger_full_merge() != 39899.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mybriefcase_bookmarks_ffi_checksum_func_update_bookmark() != 10808.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class BookmarkDto (
    var `id`: kotlin.String, 
    var `url`: kotlin.String, 
    var `title`: kotlin.String, 
    var `notes`: kotlin.String, 
    var `createdAt`: kotlin.String, 
    var `updatedAt`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBookmarkDto: FfiConverterRustBuffer<BookmarkDto> {
    override fun read(buf: ByteBuffer): BookmarkDto {
        return BookmarkDto(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: BookmarkDto) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`url`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterString.allocationSize(value.`notes`) +
            FfiConverterString.allocationSize(value.`createdAt`) +
            FfiConverterString.allocationSize(value.`updatedAt`)
    )

    override fun write(value: BookmarkDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`url`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterString.write(value.`notes`, buf)
            FfiConverterString.write(value.`createdAt`, buf)
            FfiConverterString.write(value.`updatedAt`, buf)
    }
}



data class BookmarkHistoryEntryDto (
    var `changeHash`: kotlin.String, 
    var `timestamp`: kotlin.Long, 
    var `actor`: kotlin.String, 
    var `changedFields`: List<FieldChangeDto>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBookmarkHistoryEntryDto: FfiConverterRustBuffer<BookmarkHistoryEntryDto> {
    override fun read(buf: ByteBuffer): BookmarkHistoryEntryDto {
        return BookmarkHistoryEntryDto(
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceTypeFieldChangeDto.read(buf),
        )
    }

    override fun allocationSize(value: BookmarkHistoryEntryDto) = (
            FfiConverterString.allocationSize(value.`changeHash`) +
            FfiConverterLong.allocationSize(value.`timestamp`) +
            FfiConverterString.allocationSize(value.`actor`) +
            FfiConverterSequenceTypeFieldChangeDto.allocationSize(value.`changedFields`)
    )

    override fun write(value: BookmarkHistoryEntryDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`changeHash`, buf)
            FfiConverterLong.write(value.`timestamp`, buf)
            FfiConverterString.write(value.`actor`, buf)
            FfiConverterSequenceTypeFieldChangeDto.write(value.`changedFields`, buf)
    }
}



data class BookmarkItemDto (
    var `id`: kotlin.String, 
    var `title`: kotlin.String, 
    var `url`: kotlin.String, 
    var `createdAt`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBookmarkItemDto: FfiConverterRustBuffer<BookmarkItemDto> {
    override fun read(buf: ByteBuffer): BookmarkItemDto {
        return BookmarkItemDto(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: BookmarkItemDto) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterString.allocationSize(value.`url`) +
            FfiConverterString.allocationSize(value.`createdAt`)
    )

    override fun write(value: BookmarkItemDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterString.write(value.`url`, buf)
            FfiConverterString.write(value.`createdAt`, buf)
    }
}



data class BreadcrumbDto (
    var `id`: kotlin.String, 
    var `title`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBreadcrumbDto: FfiConverterRustBuffer<BreadcrumbDto> {
    override fun read(buf: ByteBuffer): BreadcrumbDto {
        return BreadcrumbDto(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: BreadcrumbDto) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`title`)
    )

    override fun write(value: BreadcrumbDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`title`, buf)
    }
}



data class FieldChangeDto (
    var `field`: kotlin.String, 
    var `oldValue`: kotlin.String?, 
    var `newValue`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFieldChangeDto: FfiConverterRustBuffer<FieldChangeDto> {
    override fun read(buf: ByteBuffer): FieldChangeDto {
        return FieldChangeDto(
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FieldChangeDto) = (
            FfiConverterString.allocationSize(value.`field`) +
            FfiConverterOptionalString.allocationSize(value.`oldValue`) +
            FfiConverterOptionalString.allocationSize(value.`newValue`)
    )

    override fun write(value: FieldChangeDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`field`, buf)
            FfiConverterOptionalString.write(value.`oldValue`, buf)
            FfiConverterOptionalString.write(value.`newValue`, buf)
    }
}



data class FolderChildrenDto (
    var `folderTitle`: kotlin.String, 
    var `breadcrumbs`: List<BreadcrumbDto>, 
    var `folders`: List<FolderItemDto>, 
    var `bookmarks`: List<BookmarkItemDto>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFolderChildrenDto: FfiConverterRustBuffer<FolderChildrenDto> {
    override fun read(buf: ByteBuffer): FolderChildrenDto {
        return FolderChildrenDto(
            FfiConverterString.read(buf),
            FfiConverterSequenceTypeBreadcrumbDto.read(buf),
            FfiConverterSequenceTypeFolderItemDto.read(buf),
            FfiConverterSequenceTypeBookmarkItemDto.read(buf),
        )
    }

    override fun allocationSize(value: FolderChildrenDto) = (
            FfiConverterString.allocationSize(value.`folderTitle`) +
            FfiConverterSequenceTypeBreadcrumbDto.allocationSize(value.`breadcrumbs`) +
            FfiConverterSequenceTypeFolderItemDto.allocationSize(value.`folders`) +
            FfiConverterSequenceTypeBookmarkItemDto.allocationSize(value.`bookmarks`)
    )

    override fun write(value: FolderChildrenDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`folderTitle`, buf)
            FfiConverterSequenceTypeBreadcrumbDto.write(value.`breadcrumbs`, buf)
            FfiConverterSequenceTypeFolderItemDto.write(value.`folders`, buf)
            FfiConverterSequenceTypeBookmarkItemDto.write(value.`bookmarks`, buf)
    }
}



data class FolderDto (
    var `id`: kotlin.String, 
    var `title`: kotlin.String, 
    var `children`: List<kotlin.String>, 
    var `createdAt`: kotlin.String, 
    var `updatedAt`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFolderDto: FfiConverterRustBuffer<FolderDto> {
    override fun read(buf: ByteBuffer): FolderDto {
        return FolderDto(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FolderDto) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterSequenceString.allocationSize(value.`children`) +
            FfiConverterString.allocationSize(value.`createdAt`) +
            FfiConverterString.allocationSize(value.`updatedAt`)
    )

    override fun write(value: FolderDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterSequenceString.write(value.`children`, buf)
            FfiConverterString.write(value.`createdAt`, buf)
            FfiConverterString.write(value.`updatedAt`, buf)
    }
}



data class FolderItemDto (
    var `id`: kotlin.String, 
    var `title`: kotlin.String, 
    var `itemCount`: kotlin.UInt
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFolderItemDto: FfiConverterRustBuffer<FolderItemDto> {
    override fun read(buf: ByteBuffer): FolderItemDto {
        return FolderItemDto(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: FolderItemDto) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterUInt.allocationSize(value.`itemCount`)
    )

    override fun write(value: FolderItemDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterUInt.write(value.`itemCount`, buf)
    }
}



data class FolderNavDto (
    var `id`: kotlin.String, 
    var `title`: kotlin.String, 
    var `itemCount`: kotlin.UInt, 
    var `childFolderIds`: List<kotlin.String>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFolderNavDto: FfiConverterRustBuffer<FolderNavDto> {
    override fun read(buf: ByteBuffer): FolderNavDto {
        return FolderNavDto(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: FolderNavDto) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterUInt.allocationSize(value.`itemCount`) +
            FfiConverterSequenceString.allocationSize(value.`childFolderIds`)
    )

    override fun write(value: FolderNavDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterUInt.write(value.`itemCount`, buf)
            FfiConverterSequenceString.write(value.`childFolderIds`, buf)
    }
}



data class FolderNavTreeDto (
    var `rootFolderId`: kotlin.String, 
    var `folders`: List<FolderNavDto>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFolderNavTreeDto: FfiConverterRustBuffer<FolderNavTreeDto> {
    override fun read(buf: ByteBuffer): FolderNavTreeDto {
        return FolderNavTreeDto(
            FfiConverterString.read(buf),
            FfiConverterSequenceTypeFolderNavDto.read(buf),
        )
    }

    override fun allocationSize(value: FolderNavTreeDto) = (
            FfiConverterString.allocationSize(value.`rootFolderId`) +
            FfiConverterSequenceTypeFolderNavDto.allocationSize(value.`folders`)
    )

    override fun write(value: FolderNavTreeDto, buf: ByteBuffer) {
            FfiConverterString.write(value.`rootFolderId`, buf)
            FfiConverterSequenceTypeFolderNavDto.write(value.`folders`, buf)
    }
}



data class ImportResultDto (
    var `bookmarksImported`: kotlin.UInt, 
    var `foldersImported`: kotlin.UInt
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeImportResultDto: FfiConverterRustBuffer<ImportResultDto> {
    override fun read(buf: ByteBuffer): ImportResultDto {
        return ImportResultDto(
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: ImportResultDto) = (
            FfiConverterUInt.allocationSize(value.`bookmarksImported`) +
            FfiConverterUInt.allocationSize(value.`foldersImported`)
    )

    override fun write(value: ImportResultDto, buf: ByteBuffer) {
            FfiConverterUInt.write(value.`bookmarksImported`, buf)
            FfiConverterUInt.write(value.`foldersImported`, buf)
    }
}





sealed class FfiException: kotlin.Exception() {
    
    class NotFound(
        
        val `msg`: kotlin.String
        ) : FfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class InvalidInput(
        
        val `msg`: kotlin.String
        ) : FfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class IoException(
        
        val `msg`: kotlin.String
        ) : FfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class NotInitialized(
        
        val `msg`: kotlin.String
        ) : FfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class Internal(
        
        val `msg`: kotlin.String
        ) : FfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<FfiException> {
        override fun lift(error_buf: RustBuffer.ByValue): FfiException = FfiConverterTypeFfiError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiError : FfiConverterRustBuffer<FfiException> {
    override fun read(buf: ByteBuffer): FfiException {
        

        return when(buf.getInt()) {
            1 -> FfiException.NotFound(
                FfiConverterString.read(buf),
                )
            2 -> FfiException.InvalidInput(
                FfiConverterString.read(buf),
                )
            3 -> FfiException.IoException(
                FfiConverterString.read(buf),
                )
            4 -> FfiException.NotInitialized(
                FfiConverterString.read(buf),
                )
            5 -> FfiException.Internal(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: FfiException): ULong {
        return when(value) {
            is FfiException.NotFound -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is FfiException.InvalidInput -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is FfiException.IoException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is FfiException.NotInitialized -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is FfiException.Internal -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: FfiException, buf: ByteBuffer) {
        when(value) {
            is FfiException.NotFound -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is FfiException.InvalidInput -> {
                buf.putInt(2)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is FfiException.IoException -> {
                buf.putInt(3)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is FfiException.NotInitialized -> {
                buf.putInt(4)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is FfiException.Internal -> {
                buf.putInt(5)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




enum class SortOrder {

    NAME_ASC,
    NAME_DESC,
    DATE_DESC,
    DATE_ASC,
    RELEVANCE;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeSortOrder: FfiConverterRustBuffer<SortOrder> {
    override fun read(buf: ByteBuffer) = try {
        SortOrder.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: SortOrder) = 4UL

    override fun write(value: SortOrder, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeBookmarkDto: FfiConverterRustBuffer<BookmarkDto?> {
    override fun read(buf: ByteBuffer): BookmarkDto? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeBookmarkDto.read(buf)
    }

    override fun allocationSize(value: BookmarkDto?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeBookmarkDto.allocationSize(value)
        }
    }

    override fun write(value: BookmarkDto?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeBookmarkDto.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeBookmarkDto: FfiConverterRustBuffer<List<BookmarkDto>> {
    override fun read(buf: ByteBuffer): List<BookmarkDto> {
        val len = buf.getInt()
        return List<BookmarkDto>(len) {
            FfiConverterTypeBookmarkDto.read(buf)
        }
    }

    override fun allocationSize(value: List<BookmarkDto>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeBookmarkDto.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<BookmarkDto>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeBookmarkDto.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeBookmarkHistoryEntryDto: FfiConverterRustBuffer<List<BookmarkHistoryEntryDto>> {
    override fun read(buf: ByteBuffer): List<BookmarkHistoryEntryDto> {
        val len = buf.getInt()
        return List<BookmarkHistoryEntryDto>(len) {
            FfiConverterTypeBookmarkHistoryEntryDto.read(buf)
        }
    }

    override fun allocationSize(value: List<BookmarkHistoryEntryDto>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeBookmarkHistoryEntryDto.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<BookmarkHistoryEntryDto>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeBookmarkHistoryEntryDto.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeBookmarkItemDto: FfiConverterRustBuffer<List<BookmarkItemDto>> {
    override fun read(buf: ByteBuffer): List<BookmarkItemDto> {
        val len = buf.getInt()
        return List<BookmarkItemDto>(len) {
            FfiConverterTypeBookmarkItemDto.read(buf)
        }
    }

    override fun allocationSize(value: List<BookmarkItemDto>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeBookmarkItemDto.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<BookmarkItemDto>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeBookmarkItemDto.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeBreadcrumbDto: FfiConverterRustBuffer<List<BreadcrumbDto>> {
    override fun read(buf: ByteBuffer): List<BreadcrumbDto> {
        val len = buf.getInt()
        return List<BreadcrumbDto>(len) {
            FfiConverterTypeBreadcrumbDto.read(buf)
        }
    }

    override fun allocationSize(value: List<BreadcrumbDto>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeBreadcrumbDto.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<BreadcrumbDto>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeBreadcrumbDto.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFieldChangeDto: FfiConverterRustBuffer<List<FieldChangeDto>> {
    override fun read(buf: ByteBuffer): List<FieldChangeDto> {
        val len = buf.getInt()
        return List<FieldChangeDto>(len) {
            FfiConverterTypeFieldChangeDto.read(buf)
        }
    }

    override fun allocationSize(value: List<FieldChangeDto>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFieldChangeDto.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FieldChangeDto>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFieldChangeDto.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFolderItemDto: FfiConverterRustBuffer<List<FolderItemDto>> {
    override fun read(buf: ByteBuffer): List<FolderItemDto> {
        val len = buf.getInt()
        return List<FolderItemDto>(len) {
            FfiConverterTypeFolderItemDto.read(buf)
        }
    }

    override fun allocationSize(value: List<FolderItemDto>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFolderItemDto.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FolderItemDto>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFolderItemDto.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFolderNavDto: FfiConverterRustBuffer<List<FolderNavDto>> {
    override fun read(buf: ByteBuffer): List<FolderNavDto> {
        val len = buf.getInt()
        return List<FolderNavDto>(len) {
            FfiConverterTypeFolderNavDto.read(buf)
        }
    }

    override fun allocationSize(value: List<FolderNavDto>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFolderNavDto.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FolderNavDto>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFolderNavDto.write(it, buf)
        }
    }
}
    @Throws(FfiException::class) fun `addBookmark`(`folderId`: kotlin.String, `url`: kotlin.String, `title`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_add_bookmark(
        FfiConverterString.lower(`folderId`),FfiConverterString.lower(`url`),FfiConverterString.lower(`title`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `createFolder`(`parentFolderId`: kotlin.String, `title`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_create_folder(
        FfiConverterString.lower(`parentFolderId`),FfiConverterString.lower(`title`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `deleteBookmark`(`bookmarkId`: kotlin.String)
        = 
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_delete_bookmark(
        FfiConverterString.lower(`bookmarkId`),_status)
}
    
    

    @Throws(FfiException::class) fun `deleteFolder`(`folderId`: kotlin.String)
        = 
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_delete_folder(
        FfiConverterString.lower(`folderId`),_status)
}
    
    

    @Throws(FfiException::class) fun `exportHtml`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_export_html(
        _status)
}
    )
    }
    

    @Throws(FfiException::class) fun `getBookmark`(`bookmarkId`: kotlin.String): BookmarkDto? {
            return FfiConverterOptionalTypeBookmarkDto.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_get_bookmark(
        FfiConverterString.lower(`bookmarkId`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `getBookmarkHistory`(`bookmarkId`: kotlin.String): List<BookmarkHistoryEntryDto> {
            return FfiConverterSequenceTypeBookmarkHistoryEntryDto.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_get_bookmark_history(
        FfiConverterString.lower(`bookmarkId`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `getFolderChildren`(`folderId`: kotlin.String, `sortBy`: SortOrder): FolderChildrenDto {
            return FfiConverterTypeFolderChildrenDto.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_get_folder_children(
        FfiConverterString.lower(`folderId`),FfiConverterTypeSortOrder.lower(`sortBy`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `getFolderNavTree`(): FolderNavTreeDto {
            return FfiConverterTypeFolderNavTreeDto.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_get_folder_nav_tree(
        _status)
}
    )
    }
    

    @Throws(FfiException::class) fun `importHtml`(`folderId`: kotlin.String, `html`: kotlin.String): ImportResultDto {
            return FfiConverterTypeImportResultDto.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_import_html(
        FfiConverterString.lower(`folderId`),FfiConverterString.lower(`html`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `initRepo`(`dataDir`: kotlin.String, `syncDir`: kotlin.String, `clientId`: kotlin.String)
        = 
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_init_repo(
        FfiConverterString.lower(`dataDir`),FfiConverterString.lower(`syncDir`),FfiConverterString.lower(`clientId`),_status)
}
    
    

    @Throws(FfiException::class) fun `moveItem`(`itemId`: kotlin.String, `fromFolderId`: kotlin.String, `toFolderId`: kotlin.String)
        = 
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_move_item(
        FfiConverterString.lower(`itemId`),FfiConverterString.lower(`fromFolderId`),FfiConverterString.lower(`toFolderId`),_status)
}
    
    

    @Throws(FfiException::class) fun `renameFolder`(`folderId`: kotlin.String, `title`: kotlin.String)
        = 
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_rename_folder(
        FfiConverterString.lower(`folderId`),FfiConverterString.lower(`title`),_status)
}
    
    

    @Throws(FfiException::class) fun `revertBookmark`(`bookmarkId`: kotlin.String, `changeHash`: kotlin.String)
        = 
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_revert_bookmark(
        FfiConverterString.lower(`bookmarkId`),FfiConverterString.lower(`changeHash`),_status)
}
    
    

    @Throws(FfiException::class) fun `searchBookmarks`(`query`: kotlin.String, `sortBy`: SortOrder): List<BookmarkDto> {
            return FfiConverterSequenceTypeBookmarkDto.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_search_bookmarks(
        FfiConverterString.lower(`query`),FfiConverterTypeSortOrder.lower(`sortBy`),_status)
}
    )
    }
    
 fun `shutdown`()
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_shutdown(
        _status)
}
    
    

    @Throws(FfiException::class) fun `triggerFullMerge`(): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_trigger_full_merge(
        _status)
}
    )
    }
    

    @Throws(FfiException::class) fun `updateBookmark`(`bookmarkId`: kotlin.String, `url`: kotlin.String?, `title`: kotlin.String?, `notes`: kotlin.String?)
        = 
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_mybriefcase_bookmarks_ffi_fn_func_update_bookmark(
        FfiConverterString.lower(`bookmarkId`),FfiConverterOptionalString.lower(`url`),FfiConverterOptionalString.lower(`title`),FfiConverterOptionalString.lower(`notes`),_status)
}
    
    


